### PR TITLE
Add trinity support

### PR DESCRIPTION
**Pull request by haringsrob**
Not sure if the id will be the same for everyone, perhaps someone with a trinity can confirm.

### CODE REVIEW

**Comment by ws141** [comment]
Confirmed working. Please merge this in :)

**Comment by ws141** [comment]
@RaulPPelaez any chance you could have this merged in?

**Comment by Destroyer** [comment]
Done, hopefully @RaulPPelaez  doesn't mind :)

**Comment by RaulPPelaez** [comment]
Thank you guys! 
Please add yourselves to the contributor list as you see fit.
I do not own a naga anymore... Once in a while I borrow one and give the project a look, testing and such.

**Comment by ws141** [comment]
Cheers!

**Comment by haringsrob** [comment]
The power of open source :)

**Pull request merged**
